Gutr/Controllers/FavoriteController.cs
using Gutr.Models;
using Gutr.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gutr.Controllers
{
    public class FavoriteController : Controller
    {
        // GET: Favorite
        public ActionResult Index()
        {
            //var service = CreateFavoriteService();

            //var model = service.SetFavorite();
            //return RedirectToAction("AllPosts", "Note", "AllPosts");
            return View();
        }

        
        public ActionResult Favorite(int id)
        {
            //if (!ModelState.IsValid) return View(model);

            var service = CreateFavoriteService();

            var model = service.SetFavorite(id);

            //if (service.SetFavorite(model))
            //{
            //    TempData["SaveResult"] = "Your note was created.";
            //return RedirectToAction("Favorite");
            //};

            //ModelState.AddModelError("", "Note could not be created.");
            return RedirectToAction("AllPosts", "Note", "AllPosts");
            //return View(model);
        }

        public ActionResult UnFavorite(int noteId)
        {
            //if (!ModelState.IsValid) return View(model);

            var service = CreateFavoriteService();

            var model = service.UnSetFavorite(noteId);

            //if (service.SetFavorite(model))
            //{
            //    TempData["SaveResult"] = "Your note was created.";
            //return RedirectToAction("Favorite");
            //};

            //ModelState.AddModelError("", "Note could not be created.");
            return RedirectToAction("MyFavorites", "Note", "MyFavorites");
            //return View(model);
        }

        // GET: My Favorites
        [Authorize]
        public ActionResult MyFavorites()
        {
            var service = CreateFavoriteService();

            var model = service.GetMyFavorites();

            return View(model);
        }
        private FavoriteService CreateFavoriteService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new FavoriteService(userId);
            return service;
        }
    }
}

Gutr/Controllers/WebAPI/FavoriteController.cs
//using Gutr.Models;
//using Gutr.Services;
//using Microsoft.AspNet.Identity;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Net;
//using System.Net.Http;
//using System.Web.Http;

//namespace Gutr.Controllers.WebAPI
//{


//    [Authorize]
//    [RoutePrefix("api/Note")]
//    public class FavoriteController : ApiController
//    {
//        private bool SetStarState(int noteId, bool newState)
//        {
//            // Create the service
//            var userId = Guid.Parse(User.Identity.GetUserId());
//            var service = new FavoriteService(userId);

//            // Get the note
//            var detail = service.GetNoteById(noteId);

//            // Create the NoteEdit model instance with the new star state
//            var updatedNote =
//                new NoteEdit
//                {
//                    NoteId = detail.NoteId,
//                    Title = detail.Title,
//                    Content = detail.Content,
//                    IsStarred = newState
//                };

//            // Return a value indicating whether the update succeeded
//            return service.UpdateNote(updatedNote);
//        }

//        [Route("{id}/Star")]
//        [HttpPut]
//        public bool ToggleStarOn(int id) => SetStarState(id, true);

//        [Route("{id}/Star")]
//        [HttpDelete]
//        public bool ToggleStarOff(int id) => SetStarState(id, false);
//    }
//}

Gutr/Views/Favorite/AllPosts.cshtml
@model IEnumerable<Gutr.Models.NoteListItem>

@{
    ViewBag.Title = "AllPosts";
}

<h2>All Posts</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    @*<tr>
        <th>
            @Html.DisplayNameFor(model => model.userEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoteId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
        <th></th>
    </tr>*@

@foreach (var item in Model) {
    <tr>
        <td>
            @*@value = Html.DisplayFor(modelItem => item.userEmail)
            @substring = value.Substring(0, 5)*@
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.NoteId)
        </td>*@
        <td><div class="post-wrapper">
    <div><h3><a href="#">@Html.DisplayFor(modelItem => item.userEmail)</a> says:  </h3></div>
    <div class="post-message">
        @Html.DisplayFor(modelItem => item.Title)
        <a href="@Html.DisplayFor(modelItem => item.Content)" target="blank">@Html.DisplayFor(modelItem => item.Content)</a>
    </div>
    <div class="ts">@Html.DisplayFor(modelItem => item.CreatedUtc)</div>
    <div class="noteid">@Html.DisplayFor(modelItem => item.NoteId)</div>

    @Html.ActionLink("Fav", "Index", "Favorite")@*,new{ANoteId = item.NoteId})*@
    @Html.ActionLink("SetFav", "Favorite", "Favorite",new { id = item.NoteId }, null)

        @*@using (Html.BeginForm())
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">

            <input type="submit" value="Favorite" class="btn btn-default" style="padding: 10px" />
        </div>
    </div>
    }*@
</div>
        </td>
        <td>
</td>
        @*This area is for editing your own posts*@
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.NoteId }) |
            @Html.ActionLink("Details", "Details", new { id = item.NoteId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.NoteId })
        </td>*@
    </tr>
}

</table>

Gutr/Views/Favorite/Create.cshtml
@model Gutr.Models.NoteCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create Favorite</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Note Create</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gutr/Views/Favorite/MyFavorites.cshtml
@model IEnumerable<Gutr.Models.NoteListItem>

@{
                /**/

                ViewBag.Title = "MyFavorites";
}

<h2>My Favorites</h2>
<table class="table">
    @foreach (var item in Model){
        <tr>
            <td>
                @*@value = Html.DisplayFor(modelItem => item.userEmail)
                    @substring = value.Substring(0, 5)*@
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.NoteId)
                </td>*@
            <td>
                <div class="post-wrapper">
                    @*<div><h3><a href="#">@Html.DisplayFor(item.userEmail)</a> says:  </h3></div>*@
                    <div class="post-message">
                        @Html.DisplayFor(modelItem => item.Title)
                        <a href="@Html.DisplayFor(modelItem => item.Content)" target="blank">@Html.DisplayFor(modelItem => item.Content)</a>
                    </div>
                    <div class="ts">@Html.DisplayFor(modelItem => item.CreatedUtc)</div>
                    <div class="noteid">@Html.DisplayFor(modelItem => item.NoteId)</div>


                    }





                    </tr>
</table>